name: publish

on:
  push:
    branches: 
    - staging
    - main

env:
  appname: coming-soon-demo

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: 'version'
      id: version
      shell: bash
      run: |
        branchName="${GITHUB_REF#refs/heads/}"
        echo "$branchName"
        echo "::set-output name=BRANCH_NAME::$branchName"
       
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build and push image'
    - run: |
        docker build --tag ghcr.io/${{ github.actor }}/${{env.appname}}:${{ github.sha }} --tag ghcr.io/${{ github.actor }}/${{env.appname}}:${{ steps.version.outputs.BRANCH_NAME }} -f build/Dockerfile .
        docker push --all-tags ghcr.io/${{ github.actor }}/${{env.appname}}
        
    - name: 'Deploy to Azure Web App (main)'
      if: ${{ steps.version.outputs.BRANCH_NAME == 'main' }}
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{env.appname}}'
        slot-name: 'production'
        images: 'ghcr.io/${{ github.actor }}/${{env.appname}}:${{ github.sha }}'

    - name: 'Azure logout'
      run: |
        az logout
        
